use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b' # Is overwritten by ${SEARXNG_SECRET}

engines:
  - name: wolframalpha
    disabled: false
  - name: google
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: bing
    disabled: false
  - name: brave
    disabled: false
  # Disable slow/unreliable engines
  - name: google news
    disabled: true
  - name: bing news
    disabled: true
  - name: yahoo
    disabled: true
  - name: qwant
    disabled: true
  - name: seznam
    disabled: true
  - name: mojeek
    disabled: true
